namespace Smab.SmBiosInfo.Enums;

/// <summary>
/// Represents the type of a hardware slot, such as PCI, AGP, or M.2, used for connecting components to a system.
/// </summary>
/// <remarks>This enumeration provides a comprehensive list of slot types, including legacy, current, and
/// specialized slot types. It is commonly used to identify the physical or logical characteristics of a slot in
/// hardware inventory systems, diagnostics tools, or configuration utilities.</remarks>
public enum SlotType
{
	Other                       = 0x01,
	Unknown                     = 0x02,
	ISA                         = 0x03,
	MCA                         = 0x04,
	EISA                        = 0x05,
	PCI                         = 0x06,
	PCCardPCMCIA                = 0x07,
	VLVESA                      = 0x08,
	Proprietary                 = 0x09,
	ProcessorCardSlot           = 0x0A,
	ProprietaryMemoryCardSlot   = 0x0B,
	IORiserCardSlot             = 0x0C,
	NuBus                       = 0x0D,
	PCI66MHzCapable             = 0x0E,
	AGP                         = 0x0F,
	AGP2X                       = 0x10,
	AGP4X                       = 0x11,
	PCIX                        = 0x12,
	AGP8X                       = 0x13,
	M2Socket1DPMechanicalKeyA   = 0x14,
	M2Socket1SDMechanicalKeyE   = 0x15,
	M2Socket2MechanicalKeyB     = 0x16,
	M2Socket3MechanicalKeyM     = 0x17,
	MXMTypeI                    = 0x18,
	MXMTypeII                   = 0x19,
	MXMTypeIIIstandardconnector = 0x1A,
	MXMTypeIIIHEconnector       = 0x1B,
	MXMTypeIV                   = 0x1C,
	MXM30TypeA                  = 0x1D,
	MXM30TypeB                  = 0x1E,
	PCIExpressGen2SFF8639U2     = 0x1F,
	PCIExpressGen3SFF8639U2     = 0x20,
	PCIExpressMini52pinCEMspec20WithBottomSideKeepouts       = 0x21,
	PCIExpressMini52pinCEMspec20WithoutBottomSideKeepouts    = 0x22,
	PCIExpressMini76pinCEMspec20CorrespondsToDisplayMinicard = 0x23,
	PCIExpressGen4SFF8639U2     = 0x24,
	PCIExpressGen5SFF8639U2     = 0x25,
	OCPNIC30SmallFormFactorSFF  = 0x26,
	OCPNIC30LargeFormFactorLFF  = 0x27,
	OCPNICPriorto30             = 0x28,
	CXLFlexbus10Deprecated      = 0x30,
	PC98C20                     = 0xA0,
	PC98C24                     = 0xA1,
	PC98E                       = 0xA2,
	PC98LocalBus                = 0xA3,
	PC98Card                    = 0xA4,
	PCIExpress                  = 0xA5,
	PCIExpressx1                = 0xA6,
	PCIExpressx2                = 0xA7,
	PCIExpressx4                = 0xA8,
	PCIExpressx8                = 0xA9,
	PCIExpressx16               = 0xAA,
	PCIExpressGen2              = 0xAB,
	PCIExpressGen2x1            = 0xAC,
	PCIExpressGen2x2            = 0xAD,
	PCIExpressGen2x4            = 0xAE,
	PCIExpressGen2x8            = 0xAF,
	PCIExpressGen2x16           = 0xB0,
	PCIExpressGen3              = 0xB1,
	PCIExpressGen3x1            = 0xB2,
	PCIExpressGen3x2            = 0xB3,
	PCIExpressGen3x4            = 0xB4,
	PCIExpressGen3x8            = 0xB5,
	PCIExpressGen3x16           = 0xB6,
	PCIExpressGen4              = 0xB8,
	PCIExpressGen4x1            = 0xB9,
	PCIExpressGen4x2            = 0xBA,
	PCIExpressGen4x4            = 0xBB,
	PCIExpressGen4x8            = 0xBC,
	PCIExpressGen4x16           = 0xBD,
	PCIExpressGen5              = 0xBE,
	PCIExpressGen5x1            = 0xBF,
	PCIExpressGen5x2            = 0xC0,
	PCIExpressGen5x4            = 0xC1,
	PCIExpressGen5x8            = 0xC2,
	PCIExpressGen5x16           = 0xC3,
	PCIExpressGen6andBeyond     = 0xC4,
	EnterpriseandDatacenter1UE1FormFactorSlot    = 0xC5,
	EnterpriseandDatacenter3InchE3FormFactorSlot = 0xC6,
}
