namespace SmabInv.SmBios.Enums;

public enum ChassisType
{
	Other = 1,
	Unknown = 2,
	Desktop = 3,
	LowProfileDesktop = 4,
	PizzaBox = 5,
	MiniTower = 6,
	Tower = 7,
	Portable = 8,
	Laptop = 9,
	Notebook = 10,
	HandHeld = 11,
	DockingStation = 12,
	AllInOne = 13,
	SubNotebook = 14,
	SpaceSaving = 15,
	LunchBox = 16,
	MainServerChassis = 17,
	ExpansionChassis = 18,
	SubChassis = 19,
	BusExpansionChassis = 20,
	PeripheralChassis = 21,
	RAIDChassis = 22,
	RackMountChassis = 23,
	SealedCasePC = 24,
	MultiSystemChassis = 25,
	CompactPCI = 26,
	AdvancedTCA = 27,
	Blade = 28,
	BladeEnclosure = 29,
	Tablet = 30,
	Convertible = 31,
	Detachable = 32,
	IoTGateway = 33,
	EmbeddedPC = 34,
	MiniPC = 35,
	StickPC = 36
}
